AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - config.ru
    - config/**/*
    - bin/**/*

Metrics/BlockLength:
  Exclude:
    - spec/*/**

Style/Documentation:
  Enabled: false
