AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - config.ru
    - config/**/*
    - bin/**/*
    - db/schema.rb
    - db/migrate/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/*/**

Style/Documentation:
  Enabled: false
