AllCops:
  TargetRubyVersion: 3.0.0
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - config.ru
    - bin/**/*

Metrics/BlockLength:
  Exclude:
    - spec/*/**.rb
    - db/**/*.rb

Metrics/AbcSize:
  Exclude:
    - db/**/*

Metrics/MethodLength:
  Exclude:
    - db/**/*

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - db/**/*.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - db/**/*.rb

Style/NumericLiterals:
  Exclude:
    - db/**/*.rb

Style/StringLiterals:
  Exclude:
    - db/**/*.rb

Style/WordArray:
  Exclude:
    - db/**/*.rb
