AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - config.ru
    - config/**/*
    - bin/**/*
    - db/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/*/**.rb
    - db/**/*.rb

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - db/**/*.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - db/**/*.rb

Style/NumericLiterals:
  Exclude:
    - db/**/*.rb

Style/StringLiterals:
  Exclude:
    - db/**/*.rb

Style/WordArray:
  Exclude:
    - db/**/*.rb
